// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;

    public partial class AssetPairModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetPairModel class.
        /// </summary>
        public AssetPairModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetPairModel class.
        /// </summary>
        public AssetPairModel(double minVolume, double minInvertedVolume, string id = default(string), AssetModel baseAsset = default(AssetModel), AssetModel quotingAsset = default(AssetModel))
        {
            Id = id;
            BaseAsset = baseAsset;
            QuotingAsset = quotingAsset;
            MinVolume = minVolume;
            MinInvertedVolume = minInvertedVolume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAsset")]
        public AssetModel BaseAsset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuotingAsset")]
        public AssetModel QuotingAsset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MinVolume")]
        public double MinVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MinInvertedVolume")]
        public double MinInvertedVolume { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            BaseAsset?.Validate();
            QuotingAsset?.Validate();
        }
    }
}
