// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetModel
    {
        /// <summary>
        /// Initializes a new instance of the AssetModel class.
        /// </summary>
        public AssetModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetModel class.
        /// </summary>
        public AssetModel(int accuracy, bool isTradable, bool isTrusted, bool kycNeeded, string id = default(string), string displayId = default(string), string lykkeEntityId = default(string), string blockchain = default(string))
        {
            Id = id;
            DisplayId = displayId;
            Accuracy = accuracy;
            IsTradable = isTradable;
            IsTrusted = isTrusted;
            KycNeeded = kycNeeded;
            LykkeEntityId = lykkeEntityId;
            Blockchain = blockchain;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DisplayId")]
        public string DisplayId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Accuracy")]
        public int Accuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsTradable")]
        public bool IsTradable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsTrusted")]
        public bool IsTrusted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KycNeeded")]
        public bool KycNeeded { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LykkeEntityId")]
        public string LykkeEntityId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Blockchain")]
        public string Blockchain { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
