// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderAction.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum BlockchainIntegrationType
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "Bil")]
        Bil,
        [EnumMember(Value = "Sirius")]
        Sirius
    }
    internal static class BlockchainIntegrationTypeEnumExtension
    {
        internal static string ToSerializedValue(this BlockchainIntegrationType? value)  =>
            value == null ? null : ((BlockchainIntegrationType)value).ToSerializedValue();

        internal static string ToSerializedValue(this BlockchainIntegrationType value)
        {
            switch( value )
            {
                case BlockchainIntegrationType.None:
                    return "None";
                case BlockchainIntegrationType.Bil:
                    return "Bil";
                case BlockchainIntegrationType.Sirius:
                    return "Sirius";
            }
            return null;
        }

        internal static BlockchainIntegrationType? ParseBlockchainIntegrationType(this string value)
        {
            switch( value )
            {
                case "None":
                    return BlockchainIntegrationType.None;
                case "Bil":
                    return BlockchainIntegrationType.Bil;
                case "Sirius":
                    return BlockchainIntegrationType.Sirius;
            }
            return null;
        }
    }
}
