// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;

    public partial class ConfirmCommand
    {
        /// <summary>
        /// Initializes a new instance of the ConfirmCommand class.
        /// </summary>
        public ConfirmCommand()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConfirmCommand class.
        /// </summary>
        public ConfirmCommand(string confirmation = default(string))
        {
            Confirmation = confirmation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Confirmation")]
        public string Confirmation { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            
        }
    }
}
