// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateCashoutCommand
    {
        /// <summary>
        /// Initializes a new instance of the CreateCashoutCommand class.
        /// </summary>
        public CreateCashoutCommand()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateCashoutCommand class.
        /// </summary>
        public CreateCashoutCommand(System.Guid operationId, string destinationAddress, string destinationAddressExtension, double volume, AssetCashoutModel asset, ClientCashoutModel client, GlobalSettingsCashoutModel globalSettings)
        {
            OperationId = operationId;
            DestinationAddress = destinationAddress;
            DestinationAddressExtension = destinationAddressExtension;
            Volume = volume;
            Asset = asset;
            Client = client;
            GlobalSettings = globalSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationId")]
        public System.Guid OperationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DestinationAddress")]
        public string DestinationAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DestinationAddressExtension")]
        public string DestinationAddressExtension { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public AssetCashoutModel Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Client")]
        public ClientCashoutModel Client { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GlobalSettings")]
        public GlobalSettingsCashoutModel GlobalSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (DestinationAddress == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DestinationAddress");
            }
            if (DestinationAddressExtension == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DestinationAddressExtension");
            }
            if (Asset == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Asset");
            }
            if (Client == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Client");
            }
            if (GlobalSettings == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "GlobalSettings");
            }
            if (Asset != null)
            {
                Asset.Validate();
            }
            if (Client != null)
            {
                Client.Validate();
            }
            if (GlobalSettings != null)
            {
                GlobalSettings.Validate();
            }
        }
    }
}
