// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateStopLimitOrderCommand
    {
        /// <summary>
        /// Initializes a new instance of the CreateStopLimitOrderCommand
        /// class.
        /// </summary>
        public CreateStopLimitOrderCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateStopLimitOrderCommand
        /// class.
        /// </summary>
        /// <param name="orderAction">Possible values include: 'Buy',
        /// 'Sell'</param>
        public CreateStopLimitOrderCommand(double volume, decimal? lowerLimitPrice, decimal? lowerPrice, decimal? upperLimitPrice, decimal? upperPrice, OrderAction orderAction, AssetPairModel assetPair = default(AssetPairModel),  ClientModel client = default(ClientModel), GlobalSettingsModel globalSettings = default(GlobalSettingsModel))
        {
            AssetPair = assetPair;
            Volume = volume;
            LowerLimitPrice = lowerLimitPrice;
            LowerPrice = lowerPrice;
            UpperLimitPrice = upperLimitPrice;
            UpperPrice = upperPrice;
            OrderAction = orderAction;
            Client = client;
            GlobalSettings = globalSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public AssetPairModel AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LowerLimitPrice")]
        public decimal? LowerLimitPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LowerPrice")]
        public decimal? LowerPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UpperLimitPrice")]
        public decimal? UpperLimitPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UpperPrice")]
        public decimal? UpperPrice { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Buy', 'Sell'
        /// </summary>
        [JsonProperty(PropertyName = "OrderAction")]
        public OrderAction OrderAction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Client")]
        public ClientModel Client { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GlobalSettings")]
        public GlobalSettingsModel GlobalSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        public virtual void Validate()
        {
            if (AssetPair != null)
            {
                AssetPair.Validate();
            }
            if (Client != null)
            {
                Client.Validate();
            }
            if (GlobalSettings != null)
            {
                GlobalSettings.Validate();
            }
        }
    }
}
