// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateLimitOrderCommand
    {
        /// <summary>
        /// Initializes a new instance of the CreateLimitOrderCommand class.
        /// </summary>
        public CreateLimitOrderCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateLimitOrderCommand class.
        /// </summary>
        /// <param name="orderAction">Possible values include: 'Buy',
        /// 'Sell'</param>
        public CreateLimitOrderCommand(double volume, decimal price, OrderAction orderAction, AssetPairModel assetPair = default(AssetPairModel), ClientModel client = default(ClientModel), GlobalSettingsModel globalSettings = default(GlobalSettingsModel))
        {
            AssetPair = assetPair;
            Volume = volume;
            Price = price;
            OrderAction = orderAction;
            Client = client;
            GlobalSettings = globalSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public AssetPairModel AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Price")]
        public decimal Price { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Buy', 'Sell'
        /// </summary>
        [JsonProperty(PropertyName = "OrderAction")]
        public OrderAction OrderAction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Client")]
        public ClientModel Client { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GlobalSettings")]
        public GlobalSettingsModel GlobalSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AssetPair != null)
            {
                AssetPair.Validate();
            }
            if (Client != null)
            {
                Client.Validate();
            }
            if (GlobalSettings != null)
            {
                GlobalSettings.Validate();
            }
        }
    }
}
