// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateNewOrderCommand
    {
        /// <summary>
        /// Initializes a new instance of the CreateNewOrderCommand class.
        /// </summary>
        public CreateNewOrderCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateNewOrderCommand class.
        /// </summary>
        public CreateNewOrderCommand(System.Guid walletId, string clientOrderId = default(string))
        {
            WalletId = walletId;
            ClientOrderId = clientOrderId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WalletId")]
        public System.Guid WalletId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientOrderId")]
        public string ClientOrderId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
