// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreateMarketOrderCommand
    {
        /// <summary>
        /// Initializes a new instance of the CreateMarketOrderCommand class.
        /// </summary>
        public CreateMarketOrderCommand()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateMarketOrderCommand class.
        /// </summary>
        /// <param name="orderAction">Possible values include: 'Buy',
        /// 'Sell'</param>
        public CreateMarketOrderCommand(string assetId, AssetPairModel assetPair, double volume, OrderAction orderAction, ClientModel client, GlobalSettingsModel globalSettings)
        {
            AssetId = assetId;
            AssetPair = assetPair;
            Volume = volume;
            OrderAction = orderAction;
            Client = client;
            GlobalSettings = globalSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public AssetPairModel AssetPair { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public double Volume { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Buy', 'Sell'
        /// </summary>
        [JsonProperty(PropertyName = "OrderAction")]
        public OrderAction OrderAction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Client")]
        public ClientModel Client { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GlobalSettings")]
        public GlobalSettingsModel GlobalSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (AssetId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssetId");
            }
            if (AssetPair == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AssetPair");
            }
            if (Client == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Client");
            }
            if (GlobalSettings == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "GlobalSettings");
            }
            if (AssetPair != null)
            {
                AssetPair.Validate();
            }
            if (Client != null)
            {
                Client.Validate();
            }
            if (GlobalSettings != null)
            {
                GlobalSettings.Validate();
            }
        }
    }
}
