// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;

    public partial class CreateCashoutCommand
    {
        /// <summary>
        /// Initializes a new instance of the CreateCashoutCommand class.
        /// </summary>
        public CreateCashoutCommand()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateCashoutCommand class.
        /// </summary>
        public CreateCashoutCommand(System.Guid operationId, decimal volume, string destinationAddress = default(string), string destinationAddressExtension = default(string), AssetCashoutModel asset = default(AssetCashoutModel), ClientCashoutModel client = default(ClientCashoutModel), GlobalSettingsCashoutModel globalSettings = default(GlobalSettingsCashoutModel))

        {
            OperationId = operationId;
            DestinationAddress = destinationAddress;
            DestinationAddressExtension = destinationAddressExtension;
            Volume = volume;
            Asset = asset;
            Client = client;
            GlobalSettings = globalSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OperationId")]
        public System.Guid OperationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DestinationAddress")]
        public string DestinationAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DestinationAddressExtension")]
        public string DestinationAddressExtension { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public decimal Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public AssetCashoutModel Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Client")]
        public ClientCashoutModel Client { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GlobalSettings")]
        public GlobalSettingsCashoutModel GlobalSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            Asset?.Validate();
            Client?.Validate();
            GlobalSettings?.Validate();
        }
    }
}
