// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;

    public partial class CreateSwiftCashoutCommand
    {
        /// <summary>
        /// Initializes a new instance of the CreateSwiftCashoutCommand class.
        /// </summary>
        public CreateSwiftCashoutCommand()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreateSwiftCashoutCommand class.
        /// </summary>
        public CreateSwiftCashoutCommand(decimal volume, SwiftCashoutAssetModel asset = default(SwiftCashoutAssetModel), SwiftCashoutClientModel client = default(SwiftCashoutClientModel), SwiftFieldsModel swift = default(SwiftFieldsModel), SwiftCashoutSettingsModel cashoutSettings = default(SwiftCashoutSettingsModel))
        {
            Asset = asset;
            Volume = volume;
            Client = client;
            Swift = swift;
            CashoutSettings = cashoutSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public SwiftCashoutAssetModel Asset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Volume")]
        public decimal Volume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Client")]
        public SwiftCashoutClientModel Client { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Swift")]
        public SwiftFieldsModel Swift { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CashoutSettings")]
        public SwiftCashoutSettingsModel CashoutSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            Asset?.Validate();
            Client?.Validate();
            Swift?.Validate();
            CashoutSettings?.Validate();
        }
    }
}
