// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FeeSettingsModel
    {
        /// <summary>
        /// Initializes a new instance of the FeeSettingsModel class.
        /// </summary>
        public FeeSettingsModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FeeSettingsModel class.
        /// </summary>
        public FeeSettingsModel(bool feeEnabled, string targetClientId = default(string))
        {
            FeeEnabled = feeEnabled;
            TargetClientId = targetClientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FeeEnabled")]
        public bool FeeEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TargetClientId")]
        public string TargetClientId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
