// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GlobalSettingsCashoutModel
    {
        /// <summary>
        /// Initializes a new instance of the GlobalSettingsCashoutModel class.
        /// </summary>
        public GlobalSettingsCashoutModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GlobalSettingsCashoutModel class.
        /// </summary>
        public GlobalSettingsCashoutModel(bool cashOutBlocked, string ethereumHotWallet = default(string), FeeSettingsCashoutModel feeSettings = default(FeeSettingsCashoutModel))
        {
            CashOutBlocked = cashOutBlocked;
            EthereumHotWallet = ethereumHotWallet;
            FeeSettings = feeSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CashOutBlocked")]
        public bool CashOutBlocked { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EthereumHotWallet")]
        public string EthereumHotWallet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FeeSettings")]
        public FeeSettingsCashoutModel FeeSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
