// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public partial class GlobalSettingsModel
    {
        /// <summary>
        /// Initializes a new instance of the GlobalSettingsModel class.
        /// </summary>
        public GlobalSettingsModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GlobalSettingsModel class.
        /// </summary>
        public GlobalSettingsModel(bool bitcoinBlockchainOperationsDisabled, bool btcOperationsDisabled, IList<string> blockedAssetPairs = default(IList<string>), IcoSettingsModel icoSettings = default(IcoSettingsModel), FeeSettingsModel feeSettings = default(FeeSettingsModel))
        {
            BlockedAssetPairs = blockedAssetPairs;
            BitcoinBlockchainOperationsDisabled = bitcoinBlockchainOperationsDisabled;
            BtcOperationsDisabled = btcOperationsDisabled;
            IcoSettings = icoSettings;
            FeeSettings = feeSettings;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BlockedAssetPairs")]
        public IList<string> BlockedAssetPairs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BitcoinBlockchainOperationsDisabled")]
        public bool BitcoinBlockchainOperationsDisabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BtcOperationsDisabled")]
        public bool BtcOperationsDisabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IcoSettings")]
        public IcoSettingsModel IcoSettings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FeeSettings")]
        public FeeSettingsModel FeeSettings { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            IcoSettings?.Validate();
            FeeSettings?.Validate();
        }
    }
}
