// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OperationType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OperationType
    {
        [EnumMember(Value = "Transfer")]
        Transfer,
        [EnumMember(Value = "Cashout")]
        Cashout,
        [EnumMember(Value = "VisaCardPayment")]
        VisaCardPayment,
        [EnumMember(Value = "NewOrder")]
        NewOrder
    }
    internal static class OperationTypeEnumExtension
    {
        internal static string ToSerializedValue(this OperationType? value)
        {
            return value == null ? null : ((OperationType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this OperationType value)
        {
            switch( value )
            {
                case OperationType.Transfer:
                    return "Transfer";
                case OperationType.Cashout:
                    return "Cashout";
                case OperationType.VisaCardPayment:
                    return "VisaCardPayment";
                case OperationType.NewOrder:
                    return "NewOrder";
            }
            return null;
        }

        internal static OperationType? ParseOperationType(this string value)
        {
            switch( value )
            {
                case "Transfer":
                    return OperationType.Transfer;
                case "Cashout":
                    return OperationType.Cashout;
                case "VisaCardPayment":
                    return OperationType.VisaCardPayment;
                case "NewOrder":
                    return OperationType.NewOrder;
            }
            return null;
        }
    }
}
