// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OrderAction.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OrderAction
    {
        [EnumMember(Value = "Buy")]
        Buy,
        [EnumMember(Value = "Sell")]
        Sell
    }
    internal static class OrderActionEnumExtension
    {
        internal static string ToSerializedValue(this OrderAction? value)  =>
            value == null ? null : ((OrderAction)value).ToSerializedValue();

        internal static string ToSerializedValue(this OrderAction value)
        {
            switch( value )
            {
                case OrderAction.Buy:
                    return "Buy";
                case OrderAction.Sell:
                    return "Sell";
            }
            return null;
        }

        internal static OrderAction? ParseOrderAction(this string value)
        {
            switch( value )
            {
                case "Buy":
                    return OrderAction.Buy;
                case "Sell":
                    return OrderAction.Sell;
            }
            return null;
        }
    }
}
