// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PersonalDataModel
    {
        /// <summary>
        /// Initializes a new instance of the PersonalDataModel class.
        /// </summary>
        public PersonalDataModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PersonalDataModel class.
        /// </summary>
        public PersonalDataModel(string country = default(string), string countryFromID = default(string), string countryFromPOA = default(string))
        {
            Country = country;
            CountryFromID = countryFromID;
            CountryFromPOA = countryFromPOA;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public string Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CountryFromID")]
        public string CountryFromID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CountryFromPOA")]
        public string CountryFromPOA { get; set; }

    }
}
