// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SwiftCashoutClientModel
    {
        /// <summary>
        /// Initializes a new instance of the SwiftCashoutClientModel class.
        /// </summary>
        public SwiftCashoutClientModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SwiftCashoutClientModel class.
        /// </summary>
        public SwiftCashoutClientModel(System.Guid id, string kycStatus = default(string))
        {
            Id = id;
            KycStatus = kycStatus;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KycStatus")]
        public string KycStatus { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
