// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SwiftFieldsModel
    {
        /// <summary>
        /// Initializes a new instance of the SwiftFieldsModel class.
        /// </summary>
        public SwiftFieldsModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SwiftFieldsModel class.
        /// </summary>
        public SwiftFieldsModel(string bic = default(string), string accNumber = default(string), string accName = default(string), string accHolderAddress = default(string), string bankName = default(string), string accHolderCountry = default(string), string accHolderZipCode = default(string), string accHolderCity = default(string))
        {
            Bic = bic;
            AccNumber = accNumber;
            AccName = accName;
            AccHolderAddress = accHolderAddress;
            BankName = bankName;
            AccHolderCountry = accHolderCountry;
            AccHolderZipCode = accHolderZipCode;
            AccHolderCity = accHolderCity;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bic")]
        public string Bic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccNumber")]
        public string AccNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccName")]
        public string AccName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderAddress")]
        public string AccHolderAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BankName")]
        public string BankName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderCountry")]
        public string AccHolderCountry { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderZipCode")]
        public string AccHolderZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccHolderCity")]
        public string AccHolderCity { get; set; }

    }
}
