// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.Operations.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.Operations;
    using Lykke.Service.Operations.Client;
    using Lykke.Service.Operations.Client.AutorestClient;
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SwiftCashoutClientModel
    {
        /// <summary>
        /// Initializes a new instance of the SwiftCashoutClientModel class.
        /// </summary>
        public SwiftCashoutClientModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SwiftCashoutClientModel class.
        /// </summary>
        public SwiftCashoutClientModel(System.Guid id, string kycStatus)
        {
            Id = id;
            KycStatus = kycStatus;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "KycStatus")]
        public string KycStatus { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (KycStatus == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "KycStatus");
            }
        }
    }
}
